version: '3'
services:
  mongodb:
    image: mongo
    container_name: 'mongodb-service'
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
      interval: 10s
      timeout: 10s
      retries: 5
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379"
    healthcheck:
      test: redis-cli ping
  authservice:
    restart: 'on-failure'
    container_name: 'auth-service'
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - /app/node_modules
      - ./auth:/app
    depends_on:
      - mongodb
    networks:
      - backend
  profileservice:
    restart: 'on-failure'
    container_name: 'profile-service'
    build:
      context: profile
      dockerfile: Dockerfile.dev
    ports:
      - 3002:3002
    volumes:
      - /app/node_modules
      - ./profile:/app
    depends_on:
      - mongodb
    networks:
      - backend
volumes:
  mongo-volume:
networks:
  backend: