apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth
  template:
    metadata:
      labels:
        component: auth
    spec:
      containers:
        - name: auth
          image: maheshambiga/auth-service
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: JWT_SECRET
              value: "p4sta.w1th-b0logn3s3-s@uce"
            - name: MONGODB_URI
              value: "mongodb+srv://test:test@cluster0-cz0mj.mongodb.net/test?retryWrites=true&w=majority"
            - name: LOG_LEVEL
              value: "debug"

