apiVersion: v1
kind: Service
metadata:
  name: common-mongodb-database-service
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongodb
  type: NodePort
